[project]
name = "ydeployer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fire>=0.7.0",
    "pydantic>=2.10.6",
]

[project.scripts]
ydeployer = "ydeployer.cli:main"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.uv]
exclude-newer = "7d"

[tool.ruff.lint]
extend-select = ["ALL"]
ignore = [
  "ANN",
  "D",
  "T201",
  "EM101",
  "TRY003",
  "PLR2004",
  "RET505",
  "COM812",
  "TD003",
  "TD002",
]
