repos:
  - repo: local
    hooks:
      - id: deadnix
        name: deadnix
        entry: deadnix --fail
        language: system
        files: '\.nix$'
      - id: statix
        name: statix
        entry: statix check
        language: system
        files: '\.nix$'
        pass_filenames: false
      - id: treefmt
        name: treefmt
        entry: treefmt
        language: system
        pass_filenames: false
