on: [push]

jobs:
  build:
    runs-on: nix
    steps:
      - run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan git.yori.cc >> ~/.ssh/known_hosts
      - uses: actions/checkout@v4
      # - uses: actions/cache@v5
      #   with:
      #     path: |
      #       /tmp/.cache/nix
      #     key: ${{ runner.os }}-nix-cache
      - run: nix develop .#ci --command sh -c 'echo "PATH=$PATH" >> "$GITHUB_ENV"'
      - run: attic login yorick https://cache.yori.cc "${{ secrets.ATTIC_TOKEN }}"
      - run: nix-fast-build --no-nom --flake ".#hydraJobs" --attic-cache yorick
      - run: |
          branch="${GITHUB_REF_NAME}"
          for link in result-*; do
            attr="${link#result-}"
            path=$(readlink "$link")
            mosquitto_pub -q 1 -r -h frumar.vpn.yori.cc -u ci -P "${{ secrets.MQTT_PASSWORD }}" \
              -t "yorick/git/dotfiles/${branch}/${attr}" -m "$path"
            echo "yorick/git/dotfiles/${branch}/${attr} $path"
          done
