layer = "top"
height = 26
modules-left = [ "sway/workspaces", "sway/mode", "custom/spotify" ]
modules-center = [ "sway/window" ]
modules-right = [ "pulseaudio", "network", "disk", "battery", "clock", "tray" ]

["sway/workspaces"]
all-outputs = false
format = "{icon} {name}"

["sway/workspaces".format-icons]
1 = ""
2 = "#"
3 = ""
4 = ""
5 = ""
6 = ""
7 = ""
urgent = ""
focused = ""
default = ""

["sway/mode"]
format = '<span style="italic">{}</span>'

[tray]
spacing = 10

[clock]
format = "{:%a %d %b %H:%M}"
on-click = "xdg-open https://calendar.google.com"

[disk]
format = "{free} "

[battery]
format = "{capacity}% {icon}"
format-icons = [ "", "", "", "", "" ]

[battery.states]
warning = 30
critical = 15

[network]
format-wifi = "{essid} "
format-ethernet = "{ifname} "
format-disconnected = "Disconnected ⚠"
tooltip-format = "{ipaddr}"

[pulseaudio]
scroll-step = 5
format = "{volume}% {icon}"
format-bluetooth = "{volume}% {icon}"
format-muted = ""
on-click = "pkill pavucontrol; pavucontrol"
# toggle headphones
on-click-right = "~/dotfiles/bin/btoggle.sh"

[pulseaudio.format-icons]
headphones = ""
handsfree = ""
headset = ""
phone = ""
portable = ""
car = ""
default = [ "", "" ]

["custom/spotify"]
format = "{}"
escape = true
max-length = 40
on-click = "playerctl play-pause"
exec = "$HOME/dotfiles/bin/spotify_meta.sh 2> /dev/null"
